proc printto print="/PROJECTS/GENWORTH_2016/02_CODES/LST/INCLUDE_ALL.lst"
log="/PROJECTS/GENWORTH_2016/02_CODES/LOGS/INCLUDE_ALL.log"  new; run;

/***Dataloading Programs***/


%INCLUDE "/PROJECTS/GENWORTH_2016/02_CODES/DATALOAD/Load_Claims_Data.sas";
%INCLUDE "/PROJECTS/GENWORTH_2016/02_CODES/DATALOAD/Load_Response_Data.sas";
%INCLUDE "/PROJECTS/GENWORTH_2016/02_CODES/DATALOAD/Load_Static_Policy_Data.sas";
%INCLUDE "/PROJECTS/GENWORTH_2016/02_CODES/DATALOAD/Load_WI_PHASED_PLCY_REF_21OCT2016.sas";
%INCLUDE "/PROJECTS/GENWORTH_2016/02_CODES/DATALOAD/Load_KBM_Data.sas";
%INCLUDE "/PROJECTS/GENWORTH_2016/02_CODES/DATALOAD/Load_KbmCredit_Data.sas";
%INCLUDE "/PROJECTS/GENWORTH_2016/02_CODES/DATALOAD/Load_remove_dups.sas";

/**Creating the allvars and predictive variables****/

%INCLUDE "/PROJECTS/GENWORTH_2016/02_CODES/PREPROCESS/allvars_all.sas";

/**Creating the univariate****/

%INCLUDE "/PROJECTS/GENWORTH_2016/02_CODES/UNI/run_fastuni2.sas";
