%include "/PROJECTS/GENWORTH_2016/02_CODES/library.sas";
%include "/PROJECTS/GENWORTH_2016/02_CODES/common_macros.sas";


/*proc import datafile='/PROJECTS/GENWORTH_2016/RAW/DELOITTE_STATIC_POLICY_DATA.txt'*/
/*OUT=STATIC_POLICY_DATA DBMS=DLM REPLACE; DELIMITER='09'x;GETNAMES=YES;RUN;*/

proc printto print="/PROJECTS/GENWORTH_2016/02_CODES/DATALOAD/LST/LOAD_STATIC_POLICY_DATA.lst"
log="/PROJECTS/GENWORTH_2016/02_CODES/DATALOAD/LOGS/LOAD_STATIC_POLICY_DATA.log"  new; run;


DATA RAW.STATIC_POLICY_DATA;

	INFILE '/PROJECTS/GENWORTH_2016/RAW/DELOITTE_STATIC_POLICY_DATA.txt' DELIMITER='09'X MISSOVER DSD LRECL=32767 FIRSTOBS=2 ;

	INFORMAT	CUST_REF	BEST32.	;
	INFORMAT	PLCY_REF	BEST32.	;
	INFORMAT	CLIENT_GENDER	$1.00 	;
	INFORMAT	PRIMARY_INSURED_FLAG	$1.00 	;
	INFORMAT	DOB_3	MMDDYY10.	;
	INFORMAT	ISSUE_AGE	BEST32.	;
	INFORMAT	SHARED_POLICY	$1.00 	;
	INFORMAT	ORIG_APP_STATE	$2.00 	;
	INFORMAT	PREF_DISC	$1.00 	;
	INFORMAT	DERIVED_MARITAL_STATUS	$1.00 	;
	INFORMAT	IF_SPOUSE_DISC	$1.00 	;
	INFORMAT	IF_COUPLE_ISS_DISC	$1.00 	;
	INFORMAT	STATE_PARTNERSHIP	$3.00 	;
	INFORMAT	LIMITED_PAY	$1.00 	;
	INFORMAT	PAY_TERM	$5.00 	;
	INFORMAT	ALGT_FLAG	$1.00 	;
	INFORMAT	PRODUCT	$8.00 	;

	FORMAT		CUST_REF	BEST12.	;
	FORMAT		PLCY_REF	BEST12.	;
	FORMAT		CLIENT_GENDER	$1.00 	;
	FORMAT		PRIMARY_INSURED_FLAG	$1.00 	;
	FORMAT		DOB_3	MMDDYY10.	;
	FORMAT		ISSUE_AGE	BEST12.	;
	FORMAT		SHARED_POLICY	$1.00 	;
	FORMAT		ORIG_APP_STATE	$2.00 	;
	FORMAT		PREF_DISC	$1.00 	;
	FORMAT		DERIVED_MARITAL_STATUS	$1.00 	;
	FORMAT		IF_SPOUSE_DISC	$1.00 	;
	FORMAT		IF_COUPLE_ISS_DISC	$1.00 	;
	FORMAT		STATE_PARTNERSHIP	$3.00 	;
	FORMAT		LIMITED_PAY	$1.00 	;
	FORMAT		PAY_TERM	$5.00 	;
	FORMAT		ALGT_FLAG	$1.00 	;
	FORMAT		PRODUCT	$8.00 	;

	INPUT			
		CUST_REF			
		PLCY_REF			
		CLIENT_GENDER	$		
		PRIMARY_INSURED_FLAG	$		
		DOB_3
		ISSUE_AGE	
		SHARED_POLICY	$
		ORIG_APP_STATE	$
		PREF_DISC	$
		DERIVED_MARITAL_STATUS	$
		IF_SPOUSE_DISC	$
		IF_COUPLE_ISS_DISC	$
		STATE_PARTNERSHIP	$
		LIMITED_PAY	$
		PAY_TERM	$
		ALGT_FLAG	$
		PRODUCT	$
	;	

RUN;


%HTM_QCreport(RAW,STATIC_POLICY_DATA,/PROJECTS/GENWORTH_2016/02_CODES/DATALOAD/QC_STATIC_POLICY_DATA , freqsize=40, samplesize=20);

