%include "/PROJECTS/GENWORTH_2016/02_CODES/library.sas";
%include "/PROJECTS/GENWORTH_2016/02_CODES/common_macros.sas";


/****CREATING THE FLOW CHART****/
PROC SORT DATA=PRED.RESPONSE_DATA_WI NODUPKEY DUPOUT=DUPLICATES OUT=RESPONSE_DATA;BY  PLCY_REF ROUND PHASE ;RUN;

;

	DATA RESPONSE_DATA_MISSING RESPONSE_DATA_ROUND RESPONSE_DATA_PHASE;
	SET RESPONSE_DATA;
	 IF MISSING(IFA_GROUP_STATE_PROD) THEN OUTPUT RESPONSE_DATA_MISSING;
	ELSE IF UPCASE(IFA_GROUP_STATE_PROD) = "OTHER THAN FULL APPROVAL" THEN OUTPUT RESPONSE_DATA_ROUND;
	ELSE OUTPUT RESPONSE_DATA_PHASE;
	RUN;

/***FOR ROUND****/
DATA TO_BE_TRANS;
SET RESPONSE_DATA_ROUND;
KEEP PLCY_REF ROUND RESPONSE;
RUN;

PROC TRANSPOSE DATA=TO_BE_TRANS OUT=TRANS_RESPONSE(DROP=_NAME_) PREFIX=RESPONSE;
BY PLCY_REF;
VAR RESPONSE ;
RUN;

PROC TRANSPOSE DATA=TO_BE_TRANS OUT=TRANS_ROUND(DROP=_NAME_) PREFIX=ROUND;
BY PLCY_REF;
VAR ROUND ;
RUN;

 

DATA COMBINED_ANALYSIS_DATA;
MERGE TRANS_RESPONSE(IN=A) TRANS_ROUND(IN=B);
BY PLCY_REF;

RUN;
/**CHECKING IF THE THREE PHASE TAKES VALUES 1,2 AND 3 AS EXPECTED***/
PROC FREQ DATA=COMBINED_ANALYSIS_DATA;
TABLES ROUND1 ROUND2 ROUND3/MISSING;/***546 CASES WHERE ROUND2=1 AND ROUND3=2 OR ROUND3=1, 
ALSO 63700 CASE WHERE ROUND1=2 REST EVERYTHING SEEMS CORRECT***/
RUN;

/*FOR CASES WITH ROUND1=1 AT THE START WITH ROUND2=2 OR MISSING AND ROUND3=3 OR MISSING ***/
DATA COMBINED_ANALYSIS_DATA_1;
SET COMBINED_ANALYSIS_DATA;
IF ROUND1 = 1 AND ROUND2 NOT EQ 1 AND ROUND2 NOT EQ 3/**ROUND2 IS NOT EQUAL TO 3 IN ANY OF THE CASES***/
AND ROUND3 NOT EQ 1 AND ROUND3 NOT EQ 2;
RUN;


PROC FREQ DATA=COMBINED_ANALYSIS_DATA_1;
TABLES RESPONSE1*RESPONSE2*RESPONSE3/MISSING LIST;
RUN;

/***CASES WITH ROUND1=1 AND ROUND2=1(546) AND ROUND3 IS EITHER 2 OR 1(PLOICY NUMBERS :45249,452450,461841)****/
DATA COMBINED_ANALYSIS_DATA_2;
SET COMBINED_ANALYSIS_DATA;
IF ROUND1 = 1 AND ROUND2  = 1;/**ROUND2 IS NOT EQUAL TO 3 IN ANY OF THE CASES***/
RUN;


PROC FREQ DATA=COMBINED_ANALYSIS_DATA_2;
TABLES RESPONSE1*RESPONSE2*RESPONSE3/MISSING LIST;
RUN;

/*FOR CASES WITH ROUND_IND=2 AT THE START***/
/**NOTE THIS IS HAS ROUND1 =2 AND ROUND2=MISSING FOR ALL POLICIES BUT 2 FOR 1 POLICY WITH NUMBER :608309***/
DATA COMBINED_ANALYSIS_DATA_4;
SET COMBINED_ANALYSIS_DATA;
IF ROUND1 = 2 ;
RUN;


PROC FREQ DATA=COMBINED_ANALYSIS_DATA_4;
TABLES RESPONSE1*RESPONSE2*RESPONSE3/LIST MISSING;
RUN;


/***FOR PHASE****/
DATA TO_BE_TRANS_PH;
SET RESPONSE_DATA_PHASE;
KEEP PLCY_REF PHASE RESPONSE state;
RUN;

PROC TRANSPOSE DATA=TO_BE_TRANS_PH OUT=TRANS_RESPONSE_PH(DROP=_NAME_) PREFIX=RESPONSE;
BY PLCY_REF;
VAR RESPONSE ;
RUN;

PROC TRANSPOSE DATA=TO_BE_TRANS_PH OUT=TRANS_PHASE(DROP=_NAME_) PREFIX=PHASE;
BY PLCY_REF;
VAR PHASE ;
RUN;

 

DATA COMBINED_ANALYSIS_DATA_PH;
MERGE TRANS_RESPONSE_PH(IN=A) TRANS_PHASE(IN=B);
BY PLCY_REF;

RUN;
/**CHECKING IF THE THREE PHASE TAKES ALUES 1,2 AND 3 AS EXPECTED***/
PROC FREQ DATA=COMBINED_ANALYSIS_DATA_PH;
TABLES PHASE1 PHASE2 PHASE3/MISSING;/***6 CASES WHERE PHASE1=1 AND PHASE2=3 REST EVERYTHING SEEMS CORRECT(368220
425656
444679
445664
480999
481707***/
RUN;



/*FOR CASES WITH PHASE_IND=1 AT THE START AND PHASE2=2 OR MISSING AND PHASE3=3 OR MISSING*/
DATA COMBINED_ANALYSIS_DATA_PH1;
SET COMBINED_ANALYSIS_DATA_PH;
IF PHASE1 = 1 AND PHASE2 NOT EQ 1 AND PHASE2 NOT EQ 3
AND PHASE3 NOT EQ 1 AND PHASE3 NOT EQ 2;
RUN;




PROC FREQ DATA=COMBINED_ANALYSIS_DATA_PH1;
TABLES RESPONSE1*RESPONSE2*RESPONSE3/LIST MISSING;
RUN;

/**FOR POLICIES WITH FIRST PHASE=1 AND SECOND PHASE=3***/

DATA COMBINED_ANALYSIS_DATA_PH1 COMBINED_ANALYSIS_DATA_PH2;
SET COMBINED_ANALYSIS_DATA_PH;
IF PHASE1 = 1 AND PHASE2 NOT EQ 1 AND PHASE2 NOT EQ 3
AND PHASE3 NOT EQ 1 AND PHASE3 NOT EQ 2 THEN OUTPUT COMBINED_ANALYSIS_DATA_PH1;
ELSE OUTPUT COMBINED_ANALYSIS_DATA_PH2;
RUN;




PROC FREQ DATA=COMBINED_ANALYSIS_DATA_PH2;
TABLES RESPONSE1*RESPONSE2*RESPONSE3/LIST MISSING;
RUN;

/**fOR MISSING : WHAT SHOULD WE CONSIDER FOR THEM ROUND IS ALL 2 AND PHASE IS ALL 1 ANS THERE IS ONE RECORD PER POLICY***/
DATA TO_BE_TRANS_M;
SET RESPONSE_DATA_MISSING;
KEEP PLCY_REF ROUND PHASE RESPONSE STATE;
RUN;

PROC FREQ DATA=TO_BE_TRANS_M;
TABLES RESPONSE/LIST MISSING;
RUN;
