
IF RATE_INCR<25 THEN RATE_INCR_SPLIT="< 25";
ELSE IF RATE_INCR>=25 THEN RATE_INCR_SPLIT=">= 25";
IF CUM_RATE_INCR>=0 AND CUM_RATE_INCR<20 THEN CUM_RATE_INCR_SPLIT="0-20";
ELSE IF CUM_RATE_INCR>=20 AND CUM_RATE_INCR<40 THEN CUM_RATE_INCR_SPLIT="20-40";
ELSE IF CUM_RATE_INCR>=40  THEN CUM_RATE_INCR_SPLIT="40-High";
	
	AGE_SPLIT =AGE_BIN;

		IF UPCASE(IFA_GROUP_STATE_PROD) = 'FULL APPROVAL W/ PHASES'  THEN
		IFA_GROUP_STATE_PROD_SPLIT = 'FULL APPROVAL W/ PHASES';
		ELSE IF UPCASE(IFA_GROUP_STATE_PROD) = 'FULL APPROVAL' THEN
      IFA_GROUP_STATE_PROD_SPLIT = 'FULL APPROVAL';
	ELSE IF UPCASE(IFA_GROUP_STATE_PROD) = 'OTHER THAN FULL APPROVAL' THEN
		IFA_GROUP_STATE_PROD_SPLIT = 'OTHER THAN FULL APPROVAL';
	
	if missing(GENDER)or gender ="U" then GENDER_SPLIT = "UNKNOWN";
	else IF GENDER = "M" THEN GENDER_SPLIT="Male";
	else if gender = "F" then gender_split="Female";
	else if gender ="S" then gender_split="Shared";

	
	if missing(DECISION_STAGE) then DECISION_SPLIT = "Missing";
	else if DECISION_STAGE =1 then  DECISION_SPLIT ="FIRST_STAGE";
	else if DECISION_STAGE =2 then  DECISION_SPLIT ="SECOND_STAGE";
	else if DECISION_STAGE =3 then  DECISION_SPLIT ="THIRD_STAGE";


	
	if missing(ESTINC30) then INCOME_SPLIT = "UNKNOWN";
	else if ESTINC30 in ("A","B","C","D") then INCOME_SPLIT = "LESS THAN $40,000";
	else if ESTINC30 in ("E","F") then INCOME_SPLIT = "$40,000 - $59,999";
	else if ESTINC30 = ("G") then INCOME_SPLIT = "$60,000 - $74,999";
	else if ESTINC30 = ("H") then INCOME_SPLIT = "$75,000 - $99,999";
	else if ESTINC30 = ("I") then INCOME_SPLIT = "$100,000 - $124,999";
	else if ESTINC30 in ("J","K","L","M","N","O") then INCOME_SPLIT = "$125,000+";

	if missing(STATE)  then  STATE_SPLIT = "UNKNOWN";
	else if STATE="CA" then STATE_SPLIT = "CA";
	else if STATE="NY" then STATE_SPLIT = "NY";
	else if STATE="PA" then STATE_SPLIT = "PA";
	else if STATE="IL" then STATE_SPLIT = "IL";
	else if STATE="TX" then STATE_SPLIT = "TX";
	else STATE_SPLIT="OTHERS";
